### ISSUE TITLE
MainActivity.cs is missing in the project, can't run the project ?

### ISSUE THREAD

**Issue by ghost** [XamarinUniversity/XAM312#1]
When I run the project in Visual Studio, It doesn't have MainActivity.cs. It's not compiling in the first place.

Please check and provide a fix.

**Comment by adrianstevens** [comment]
Hi @anirugu I'm sorry you're having trouble with one of the solutions. MainActivity.cs is present in each Android head project and I've manually tested every project to ensure they build on Visual Studio 2017 (v15.5.1).

I'd recommend re-downloading or re-cloning the code and trying again.

If you continue to have trouble, please provide details about your development environment (Windows or Mac, Visual Studio version etc.), which exercise(s) isn't compiling and include any error messages you're seeing.
